title: Boats & Cranes
description: Professional boat crane services
baseurl: ""
url: "https://hunsbeth.com"
domain: hunsbeth.com

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed
  sass_dir: _sass 

google_calendar:
  api_key: "AIzaSyBjijNYbPIcNAaKBbJwgVPg3u3H6nW4ZAA"
  calendar_id: "boats-cranes@boats-445515.iam.gserviceaccount.com"